name: Auto tester
on: [pull_request]
jobs:
  run-c-challenges:
    runs-on: ubuntu-latest
    container: 
      image: luisferreira32/crunner:latest
      options: --user root # workaround for known permissions issue in checkout action
    steps:
      - run: pwd
      - run: ls -ahl
      - run: whoami

      - name: Checkout
        uses: actions/checkout@v3

      - run: git status
      
      - name: Compile and build code
        run: make compile build