name: Auto tester
on: [pull_request]
env:
  RUNNER_BIN: /bin/runner
jobs:
  run-c-challenges:
    runs-on: ubuntu-latest
    container: 
      image: luisferreira32/crunner:latest
      options: --user root # workaround for known permissions issue in checkout action
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 2
      
      - name: Compile and build code
        run: make compile build

      - id: check_diffs
        run: |
          git diff --name-only HEAD..origin/main | python scripts/prcheck.py
          content=`cat run.json`
          echo "::set-output name=torun::$content"
      
      - name: Run changes
        run: |
          cat run.json | jq
          echo "${{fromJson(steps.check_diffs.outputs.torun)}}"
          $(pwd)/$RUNNER_BIN --ch anagram1 --sv solver1