name: Auto tester
on: [pull_request]
env:
  RUNNER_BIN: /bin/runner
jobs:
  run-c-challenges:
    runs-on: ubuntu-latest
    container: 
      image: luisferreira32/crunner:latest
      options: --user root # workaround for known permissions issue in checkout action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Compile and build code
        run: make compile build

      - run: git diff main
      
      - name: Run changes
        run: $(pwd)/$RUNNER_BIN --ch anagram1 --sv solver1