name: Auto tester
on: [pull_request]
jobs:
  run-c-challenges:
    runs-on: ubuntu-latest
    container: 
      image: luisferreira32/crunner:latest
      volumes:
        - $GITHUB_WORKSPACE:/home/runner/c-code-challenges/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Compile and build code
        run: make compile build